# Generated by Django 5.2.7 on 2025-11-01 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_price_buy_alter_product_price_sell'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'stocklevel',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['product', 'location'], name='stocklevel_product_f8c1fb_idx')],
                'unique_together': {('product', 'location')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('RECEIVED_FROM_SUPPLIER', 'Received from supplier'), ('SOLD_TO_CLIENT', 'Sold to client'), ('MANUAL_ADJUSTMENT', 'Manual adjustment'), ('TRANSFER', 'Transfer'), ('CORRECTION', 'Correction')], max_length=50)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'stockmovement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='stockmoveme_product_7c5195_idx')],
            },
        ),
    ]
