# Generated by Django 5.2.7 on 2025-12-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklevel',
            name='location',
            field=models.CharField(default='Main Warehouse', max_length=255),
        ),
    ]
