# Generated by Django 5.2.7 on 2026-01-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_warehouse_remove_stockmovement_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['id']},
        ),
    ]
