# Generated by Django 5.2.7 on 2026-03-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_warehouse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevel',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
