# Generated by Django 5.2.7 on 2025-11-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_buy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sell',
            field=models.FloatField(),
        ),
    ]
