# Generated by Django 5.2.7 on 2026-02-21 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_alter_product_sku'),
        ('warehouse', '0004_alter_warehouse_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('TRANSFER', 'Warehouse transfer'), ('OUTBOUND', 'Outbound to address')], db_index=True, default='TRANSFER', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('IN_TRANSIT', 'In transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('destination_address', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_created', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_sent', to='warehouse.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments_received', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('PCS', 'pcs'), ('KG', 'kg'), ('L', 'l')], default='PCS', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='product.product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipment.shipment')),
            ],
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'created_at'], name='shipment_sh_status_330280_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['from_warehouse', 'status'], name='shipment_sh_from_wa_a461f0_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['to_warehouse', 'status'], name='shipment_sh_to_ware_98b7db_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment', 'product'), name='uniq_product_per_shipment'),
        ),
    ]
